apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: location-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: location-service
  template:
    metadata:
      labels:
        run: location-service
    spec:
      containers:
      - image: us.icr.io/living-on-the-cloud/location-service:latest
        name: location-service
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:  
  name: location-service-node-port
spec:
  selector:    
    run: location-service
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31416
    protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
type: Opaque
data:
  username: a2hnd3VyYmw=
  password: RW9nWnpFckJudFZFV3BjRV9VTlRPUVpXblZmb0M4MDM=