---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: location-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: location-service
  template:
    metadata:
      labels:
        run: location-service
    spec:
      containers:
      - image: us.icr.io/living-on-the-cloud/location-service:latest
        name: location-service
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30